name: Feature request
description: Do you need a new feature or tool?
title: "[FEATURE] "
labels: [ "Status: Unverified", "Type: Feature request" ]
assignees: 'xdec0de'
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: This steps are required in order to request a new feature
      options:
        - label: I have checked that this feature isn't already requested
          required: true
        - label: I am using the latest version of 42ghcr and this feature doesn't exist
          required: true

  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: Explain the new feature / change, be as detailed as possible.
      placeholder: I would like to have lcov installed.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Why do you want this feature?
      description: Explain why this feature should be added.
      placeholder: lcov is a very useful tool to generate coverage reports!
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional information
      description: Anything that may help, such as how this feature could be used or implemented.
      placeholder: The install command is sudo apt install lcov
    validations:
      required: false

